### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by GeorgeRNG** [DFOnline/CodeClient#91]
- [ ] Auto lagslayer
- [ ] On-screen lagslayer
- [ ] Hide variable scope message
- [ ] Variable scope under name
- [ ] Destroy item /reset
- [ ] Scroll on number to change
- [ ] /dfgive
- [ ] /itemdata
- [ ] /node
- [ ] Preview item tags
